export default [
    {
      id: 'apple',
      name: 'Apple',
      description: 'iPhone, iPad, Mac, and more',
      language:'Entrar',
      country: 'United States',
      ratingAverage: 4.8,
      reviewCount: 15000,
      logoUrl: 'https://example.com/apple-logo.png',
      backgroundColor: '#f0f0f0',
      textColor: '#333',
    },
    {
      id: 'samsung',
      name: 'Samsung',
      description: 'Galaxy phones and electronics',
      language:'Entrar',
      country: 'South Korea',
      ratingAverage: 4.6,
      reviewCount: 12000,
      logoUrl: 'https://example.com/samsung-logo.png',
      backgroundColor: '#e3f2fd',
      textColor: '#003c8f',
    },
    {
      id: 'google',
      name: 'Google',
      description: 'Pixel phones and Android OS',
      language:'Entrar',
      country: 'United States',
      ratingAverage: 4.5,
      reviewCount: 9000,
      logoUrl: 'https://example.com/google-logo.png',
      backgroundColor: '#e8f5e9',
      textColor: '#00796b',
    },
    {
      id: 'huawei',
      name: 'Huawei',
      description: 'Huawei and Honor smartphones',
      language:'Entrar',
      country: 'China',
      ratingAverage: 4.3,
      reviewCount: 8000,
      logoUrl: 'https://example.com/huawei-logo.png',
      backgroundColor: '#ffecb3',
      textColor: '#f57c00',
    },
    {
      id: 'oneplus',
      name: 'OnePlus',
      description: 'OnePlus phones and accessories',
      language:'Entrar',
      country: 'China',
      ratingAverage: 4.7,
      reviewCount: 6000,
      logoUrl: 'https://example.com/oneplus-logo.png',
      backgroundColor: '#e0f2f1',
      textColor: '#009688',
    },
  ];